name: .NET Framework

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with msbuild
      run: MSBuild.exe OpenUserSecrets.csproj -p:Configuration=Release
      working-directory: $Env:GITHUB_WORKSPACE\src\OpenUserSecrets
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          path: '**\*.vsix'
